### ISSUE TITLE
ААААА РАЗНЫЕ КАВЫЧКИ В ОДНОМ ФАЙЛЕ

### ISSUE THREAD

**Issue by D1midr0sh** [Rhombus-H/lyceum_equalizer#6]
в main.py то одинарные, то двойные кавычки... ничему Сашу Django не учит...

**Comment by Rhombus-H** [comment]
Меня отчислили оттуда

**Comment by D1midr0sh** [comment]
ты хотя бы ишьсы закрывай как невыполнимые а не как выполненые
